services:
  prestashop:
    image: prestashop/prestashop:1.7.8  
    container_name: prestashop
    depends_on:
      - db
    ports:
      - "8080:80"
      - "8443:443"
    environment:
        - PS_DEV_MODE=1
        - DB_SERVER=db
        - DB_NAME=prestashop
        - DB_USER=prestashop
        - DB_PASSWD=prestashop
        - PS_LANGUAGE=en
        - PS_COUNTRY=US
        - PS_FOLDER_ADMIN=admin
        - PS_FOLDER_INSTALL=install
        - PS_SSL_ENABLED=1
    volumes:
      - ./prestashop:/var/www/html:Z
      - ./ssl:/etc/apache2/ssl
      - ./config/php/ssl.conf:/etc/apache2/sites-available/ssl.conf
    restart: unless-stopped
    command: /bin/bash -c "a2enmod ssl && a2ensite ssl && apache2-foreground"

  db:
    image: mariadb:10.6
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    command: --max_allowed_packet=64M
    volumes:
      - dbdata:/var/lib/mysql
  
volumes:
  dbdata:
